config/routes.rb
Rails.application.routes.draw do
root 'top#top'
resources :books

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
validates :title, presence: true
validates :body, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "Book was successfully created."
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book)
   else
    render :edit
   end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
    flash[:notice] = "Book was successfully destroyed."
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
def top
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<!-- form_with部分 -->
<%= form_with model:@book, local: true do |f| %>
<% if @book.errors.any? %>
<%= @book.errors.count %> errors prohibited this book from being saved:
<% @book.errors.full_messages.each do |message| %>
<%= message %>
<% end %>
<% end %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <p><%= f.submit 'Update Book' %></p>
<% end %>


<a class="Show" href=<%= book_path(@book.id) %>>Show</a>
|
<a class="back" href="/books">back</a>

app/views/books/index.html.erb
 <% if flash[:notice] %>
     <p id="notice">
         <font color="green">
       <%= flash[:notice] %>
       </font>
     </p>
   <% end %>

<h2>Books</h2>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Body</th>
        </tr>
    </thead>
    <% @books.each do |book| %>
    <tbody>
        <tr>
            <td><%= book.title %></td>
            <td><%= book.body %></td>
            <td>
              <a class="Show" href=<%= book_path(book.id) %>>Show</a>

              </td>
            <td><%= link_to "Edit", edit_book_path(book.id) %></td>
            <td><%= link_to "destroy", book_path(book.id), method: :delete,data: { confirm: 'Are you sure?' } %></td>
        </tr>
    </tbody>
    <% end %>
</table>


<h2>New book</h2>

<!-- form_with部分 -->
<%= form_with model:@book, url:'/books', local:true do |f| %>
<% if @book.errors.any? %>
<%= @book.errors.count %> errors prohibited this book from being saved:
<% @book.errors.full_messages.each do |message| %>
<%= message %>
<% end %>
<% end %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>
<br>
  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/new.html.erb
<h1>miss!</h1>

app/views/books/show.html.erb
 <% if flash[:notice] %>
   <p id="notice">
    <font color="green">
       <%= flash[:notice] %>
    </font>
   </p>
   <% end %>
<p>Title: <%= @book.title %></p>


<p>Body:　<%= @book.body %></p>

<a class="Edit" href=<%= edit_book_path(@book.id) %>>Edit</a>
|
<a class="back" href="/books">Back</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/top.html.erb
<h1>
  ようこそ
  <strong>Bookers</strong>
  へ！
  </h1>

<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や</p>

<p>印象を共有し交換することができます</p>

<a href="/books">start</a>